IntegratedBreedingPlatform/Workbench

src/main/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/GenotypeFactorValueChangeListener.java
src/main/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/SSAEnvironmentsFooterCheckboxListener.java
src/main/java/org/generationcp/ibpworkbench/ui/breedingview/singlesiteanalysis/SingleSiteAnalysisEnvironmentsComponent.java
src/test/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/GenotypeFactorValueChangeListenerTest.java
src/test/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/SSAEnvironmentsFooterCheckboxListenerTest.java
src/test/java/org/generationcp/ibpworkbench/ui/breedingview/singlesiteanalysis/SingleSiteAnalysisEnvironmentsComponentTest.java

Validate only selected environments

---

src/main/java/org/generationcp/ibpworkbench/ui/dashboard/listener/LaunchProgramAction.java
src/main/java/org/generationcp/ibpworkbench/ui/programadministration/ProgramAdministrationPanel.java
src/main/java/org/generationcp/ibpworkbench/ui/project/create/AddProgramView.java
src/main/java/org/generationcp/ibpworkbench/ui/project/create/CreateProjectPanel.java
src/test/java/org/generationcp/ibpworkbench/ui/project/create/CreateProjectPanelTest.java

Includes: 
https://github.com/IntegratedBreedingPlatform/Commons/pull/231

IBP-3022 - Enable members tab and reloading authorities when creating a new program

---

src/main/java/org/generationcp/ibpworkbench/ui/programmethods/MethodView.java

IBP-3045 - Configs lost when editing breeding method

---

src/main/java/org/generationcp/ibpworkbench/ui/WorkbenchMainView.java
src/test/java/org/generationcp/ibpworkbench/ui/WorkbenchMainViewTest.java

IBP-2823 infoicon

---

src/main/java/org/generationcp/ibpworkbench/ui/programlocations/ProgramLocationsView.java

corrected spelling of addRestrictedComponents
IBP-3115-fixPermission

IBP-3115-Fix Add Location Permission

---

src/main/java/org/generationcp/ibpworkbench/cross/study/adapted/dialogs/SaveToListDialog.java
src/main/resources/applicationContext.xml
src/test/java/org/generationcp/ibpworkbench/cross/study/adapted/dialogs/SaveToListDialogTest.java

Multi-trait query result set group name field with cross expansion. Fix null pointer exception on list saved.

IBP-2459 fill with cross expansion

---

src/main/resources/applicationContext.xml

IBP-3220 Declare studyService bean

---

src/main/web/package.json
src/main/web/yarn.lock

Upgrade typescript
Added @types dependencies

IBP-3189 Migrate from typings to @types

---

src/main/web/src/pages/BrAPI-Graphical-Filtering/main.js

…more as it is already recognized as Not Available in OpenCPU.
Parse the trait string value to Number to support floating numbers. Remove conversion of non-numeric string to zero.
IBP-3297

IBP-3297 Change the shipped OpenCPU dataset transformation presets.

---

src/main/jhipster/yarn.lock
src/main/web/yarn.lock

Update yarn.lock files

---

src/main/java/org/generationcp/ibpworkbench/ui/programlocations/ProgramLocationsPresenter.java
src/test/java/org/generationcp/ibpworkbench/ui/programlocations/ProgramLocationsPresenterTest.java

Hi @nahuel-soldevilla and @clarysabel 
In this PR we have made a changed of the method name getFilteredLocations to getFilteredLocationsDetails.
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/287
https://github.com/IntegratedBreedingPlatform/Middleware/pull/743
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/12

IBP-2974 Import Lots.

---

src/main/java/org/generationcp/ibpworkbench/controller/GraphicalFilteringController.java
src/main/resources/workbench.properties
src/main/web/src/pages/BrAPI-Graphical-Filtering/index.html
src/main/web/src/pages/BrAPI-Graphical-Filtering/main.js

Use pagedresult.max.page.size property.

IBP-3248-BrApiMaxPageSize

---

src/main/web/src/apps/ontology/app-components/variables-view/variablesView.js
src/main/web/test/app-components/variablesViewTest.js

Modify Karma test to pass filter test
IBP-3641-FilterById

IBP-3641 Filter By Id

---

src/main/java/org/generationcp/ibpworkbench/ui/programmembers/ProgramMembersPanel.java
src/test/java/org/generationcp/ibpworkbench/ui/programmembers/ProgramMembersPanelTest.java

Apply filtering of workbench project when displaying roles in program admin

IBP-3644 FilterRolesByWorkbenchProject

---

pom.xml
src/main/web/package.json
src/main/web/yarn.lock

Fixed by https://github.com/IntegratedBreedingPlatform/brapi-fieldmap/commit/53108a4bf3cdaf681f6f918def2693f573f388dd
Just upgrading the version here

IBP-3681 geojson exclude means and plants

---

pom.xml
src/main/web/src/appsNg2/admin/app/shared/services/role.service.ts

IBP-3459 API Permissions

---

src/main/jhipster/src/main/webapp/index.html

Fix Inventory Manager Label Printing Drag and Drop Function

---

src/main/java/org/generationcp/breeding/manager/containers/GermplasmQuery.java
src/main/java/org/generationcp/breeding/manager/listmanager/GermplasmSearchBarComponent.java
src/main/java/org/generationcp/breeding/manager/listmanager/GermplasmSearchResultsComponent.java
src/main/java/org/generationcp/breeding/manager/listmanager/listeners/FillWithMenuItemClickListener.java

Migrate chagnes from Breeding Manager to Workbench

IBP-1971 IBP-3875 MigratetoWorkbench

---

src/main/java/org/generationcp/breeding/manager/listimport/SpecifyGermplasmDetailsComponent.java

Hi @clarysabel.
I just set as default choice Select existing germplasm whenever found. When import Germplasm.
Please review.
Regards, Diego

IBP-3543 set as default choice Select existing germplasm whenever found.

---

src/main/java/org/generationcp/breeding/manager/listmanager/util/GermplasmListExporter.java
src/test/java/org/generationcp/breeding/manager/listmanager/util/GermplasmListExporterTest.java

- Included "added columns" in csv export based on the information available in currentColumnsInfo (to be consistent with the Excel export, because it's also avaialable in listDataTable properties)
- TODO verify FGID/MGID exclusion
Excel export: https://github.com/IntegratedBreedingPlatform/Commons/pull/269

IBP-3808 Manage Germplasm "Added columns" CSV export

---

src/main/jhipster/src/main/webapp/app/shared/inventory/service/transaction.service.ts

In this  PR I updated the URL to confirm the deposit. Replace confirmed-deposits-lists by confirmed-deposits/generation.
Include:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/57
https://github.com/IntegratedBreedingPlatform/Middleware/pull/843
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/370
Regards, Diego

IBP-3759 Import Deposit

---

src/main/jhipster/src/main/webapp/app/app.constants.ts
src/main/jhipster/src/main/webapp/app/entities/sample/sample-manager.component.html
src/main/jhipster/src/main/webapp/app/entities/sample/sample-manager.component.ts
src/main/jhipster/src/main/webapp/app/shared/service/help.service.ts
src/main/jhipster/src/main/webapp/app/shared/shared.module.ts
src/main/jhipster/src/main/webapp/content/css/global.css
src/main/web/src/appsNg2/admin/app/app.component.ts
src/main/web/src/appsNg2/admin/app/app.constants.ts
src/main/web/src/appsNg2/admin/app/shared/components/header/site-admin-header.component.html
src/main/web/src/appsNg2/admin/app/shared/components/header/site-admin-header.component.ts
src/main/web/src/appsNg2/admin/app/shared/services/help.service.ts

Help Links for 
1. Site Admin 
2. Manage Samples

IBP-3724-HelpLinks

---

src/main/web/src/apps/ontology/app-components/add-formula-view/addFormulaView.html
src/main/web/src/apps/ontology/app-components/add-formula-view/addFormulaView.js
src/main/web/src/apps/ontology/app-services/utilities.js
src/main/web/src/appsNg2/admin/app/shared/components/header/site-admin-header.component.html

Help link icon in create/edit formula

IBP-3701-IBP-3724-HelpLinks

---

src/main/java/org/generationcp/breeding/manager/customcomponent/SaveListAsDialog.java

Revert code for overwriting. 
Overwrite only if selected list is an existing list

IBP-1711-SeteCurrentlySavedGermplasmList

---

src/main/web/src/appsNg2/admin/app/app.style.css

Added css to remove selected option from select2

IBP-2809-SelectedOptionStyle

---

src/main/java/org/generationcp/breeding/manager/listmanager/listcomponent/ListViewActionMenu.java
src/main/java/org/generationcp/browser/study/containers/StudyButtonRenderer.java
src/main/java/org/generationcp/ibpworkbench/controller/AccessNoAvailableController.java
src/main/java/org/generationcp/ibpworkbench/germplasm/containers/ListsForGermplasmQuery.java
src/main/java/org/generationcp/ibpworkbench/sample/SampleInfoComponent.java
src/main/java/org/generationcp/ibpworkbench/ui/dashboard/WorkbenchDashboard.java
src/main/jhipster/src/main/webapp/app/entities/sample/sample.route.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-manager.route.ts
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.route.ts
src/main/web/src/appsNg2/admin/app/roles/role-card.component.spec.ts
src/main/web/src/pages/accessNotAvailable.html
src/main/webapp/WEB-INF/spring-security.xml

Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/401
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/919
https://github.com/IntegratedBreedingPlatform/Middleware/pull/887
Regard, Diego

IBP-3980 left side menu reorganization

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-creation.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-creation.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-type.model.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list.service.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-manager.context.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-manager.module.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-manager.route.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.ts
src/main/jhipster/src/main/webapp/app/shared/model/germplasm-list.ts
src/main/jhipster/src/main/webapp/app/shared/shared.module.ts
src/main/jhipster/src/main/webapp/app/shared/tree/germplasm/germplasm-tree-table.service.ts
src/main/jhipster/src/main/webapp/i18n/en/germplasm-manager.json
src/main/jhipster/src/main/webapp/i18n/en/global.json

germplasm list save modal with some options for reuse in non-modal contexts

IBP-3944 save germplasm list

---

src/main/java/org/generationcp/breeding/manager/listmanager/util/GermplasmListExporter.java
src/test/java/org/generationcp/breeding/manager/listmanager/GermplasmSearchResultsComponentTest.java
src/test/java/org/generationcp/breeding/manager/listmanager/ListBuilderComponentTest.java
src/test/java/org/generationcp/breeding/manager/listmanager/ListComponentTest.java
src/test/java/org/generationcp/breeding/manager/listmanager/util/GermplasmListExporterTest.java
src/test/java/org/generationcp/ibpworkbench/germplasm/inventory/InventoryViewComponentTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/911
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/939
https://github.com/IntegratedBreedingPlatform/Commons/pull/284
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/416
Please, review
Regards, Diego

IBP-4058 Remove StockID variable from the ontology

---

src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

Fix applied in front end to follow brapi specification for entryType

IBP-4105-BrapiGraphicalNullEntryType

---

src/main/java/org/generationcp/ibpworkbench/controller/ApiAuthenticationService.java
src/main/java/org/generationcp/ibpworkbench/controller/Token.java
src/main/java/org/generationcp/ibpworkbench/controller/TokenRequest.java
src/test/java/org/generationcp/ibpworkbench/controller/ApiAuthenticationServiceTest.java

In this PR I changed authentication login to the /token resource.
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/433
Please review.
Regards, Diego

IBP-4043 authenticate url

---

src/main/jhipster/src/main/webapp/app/entities/sample/sample.route.ts

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/933
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/437
Regards, Diego

IBP- 4151 Fixing SAMPLES LISTS permission

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.html

Improves #396 
Issue: IBP-4150

Improve "items per page" on small screens

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.ts

Include it in confirmation popup
cc @darla-leafnode

IBP-4150 Consider "ends with" as expensive filter

---

src/main/jhipster/src/main/webapp/app/entities/sample/sample-import-plate-mapping.component.ts
src/main/jhipster/src/main/webapp/app/entities/sample/sample-import-plate.component.ts
src/main/jhipster/src/main/webapp/app/entities/sample/sample-search-list.component.ts
src/main/jhipster/src/main/webapp/app/entities/sample/sample.component.ts
src/main/jhipster/src/main/webapp/app/entities/sample/tree-table/tree-table.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-import-update-dialog.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-add.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-creation.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/details/inventory-details.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/selector/germplasm-selector.component.ts
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.ts
src/main/jhipster/src/main/webapp/app/shared/column-filter/column-filter.component.ts
src/main/jhipster/src/test/javascript/spec/app/entities/sample/sample-import-plate-mapping.component.spec.ts
src/main/jhipster/src/test/javascript/spec/app/entities/sample/sample-import-plate.component.spec.ts
src/main/jhipster/src/test/javascript/spec/helpers/mock-alert.service.ts
src/main/jhipster/src/test/javascript/spec/test.module.ts

AlertService as an adapter for JhiAlertService.addAlert, that doesn't
close automatically

IBP-4159 Permanent error messages. Use AlertService

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/lot-creation-dialog.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/lot-creation-dialog.component.ts
src/main/web/package.json

Front end changes to add loading icon when saving. 
When user clicks save and process is not yet complete, loading icon is displayed and save button is disabled to avoid user double clicking the button

IBP-4003-SelectAllPages

---

src/main/java/org/generationcp/ibpworkbench/ui/programlocations/ProgramLocationsPresenter.java
src/test/java/org/generationcp/ibpworkbench/ui/programlocations/ProgramLocationsPresenterTest.java

renamed location.uniqueID by location.programUUID

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/selector/germplasm-selector.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/selector/germplasm-selector.component.ts
src/main/jhipster/src/main/webapp/app/shared/column-filter/column-filter.component.ts

@nahuel-soldevilla,
When removing column filter, check if filter is attributes or name types to remove correct column filter
cc: @darla-leafnode 
----
_Nahuel_: I added some improvements on tops of gelli's changes.
- Handle clear sort inside main components instead of column-filter
- Consolidate all sort keys into ColumnLabels enum

IBP-4231 Fix clear sort issues

---

src/main/java/org/generationcp/breeding/manager/listimport/actions/SaveGermplasmListAction.java

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/963

 IBP-3935 Removing previousAmount column from ims_transaction table.

---

src/main/java/org/generationcp/ibpworkbench/cross/study/adapted/dialogs/ViewTraitObservationsDialog.java
src/main/java/org/generationcp/ibpworkbench/cross/study/traitdonors/main/TraitDisplayResults.java
src/test/java/org/generationcp/ibpworkbench/cross/study/traitdonors/main/TraitDisplayResultsTest.java

If numeric trait has invalid value, ignore value (same treatment to "missing" value) 
Unit test

IBP-3004-TraitInvalidValue

---

src/main/java/org/generationcp/breeding/manager/listmanager/ListComponent.java
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/lot-creation-dialog.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/lot-creation-dialog.component.ts
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.css
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.html
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.ts
src/main/jhipster/src/main/webapp/app/shared/modal/modal-confirm.component.ts

- label printing
- lot creation component

IBP-4093 migration angular components to bootstrap 4

---

src/main/java/org/generationcp/ibpworkbench/cross/study/traitdonors/main/TraitDisplayResults.java
src/test/java/org/generationcp/ibpworkbench/cross/study/traitdonors/main/TraitDisplayResultsTest.java

Remove function getSortedGermplasmList (grouping of germplasm by name)

IBP-4290-DuplicateGermplasmPreferredName

---

src/main/java/org/generationcp/ibpworkbench/ui/dashboard/WorkbenchDashboard.java
src/test/java/org/generationcp/ibpworkbench/ui/dashboard/WorkbenchDashboardTest.java

Replaced getProjectsByUser with getProjects

IBP-4338-BrapiGetProgramsV2

---

src/main/jhipster/src/main/webapp/app/entities/program/program.component.html
src/main/jhipster/src/main/webapp/app/navbar/navbar.component.html

IBP-4400 fix look and feel wrapper navbar and sidebar

---

src/main/java/org/generationcp/breeding/manager/customcomponent/ExportListAsDialog.java
src/main/java/org/generationcp/ibpworkbench/actions/OpenSelectDatasetForExportAction.java
src/main/java/org/generationcp/ibpworkbench/actions/RunMultiSiteAction.java
src/main/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/RunSingleSiteAction.java
src/main/java/org/generationcp/ibpworkbench/study/RepresentationDatasetComponent.java
src/main/java/org/generationcp/ibpworkbench/util/MultiSiteDataExporter.java
src/test/java/org/generationcp/breeding/manager/customcomponent/ExportListAsDialogTest.java
src/test/java/org/generationcp/ibpworkbench/actions/RunMultiSiteActionTest.java
src/test/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/RunSingleSiteActionTest.java
src/test/java/org/generationcp/ibpworkbench/util/MultiSiteDataExporterTest.java

Implement Filenamegenerator new parameters

IBP-4339-ValidateFilenameGenerator

---

src/test/java/org/generationcp/breeding/manager/customcomponent/ExportListAsDialogTest.java
src/test/java/org/generationcp/ibpworkbench/actions/OpenSelectDatasetForExportActionTest.java
src/test/java/org/generationcp/ibpworkbench/actions/RunMultiSiteActionTest.java
src/test/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/RunSingleSiteActionTest.java
src/test/java/org/generationcp/ibpworkbench/cross/study/h2h/main/ResultsComponentTest.java
src/test/java/org/generationcp/ibpworkbench/study/RepresentationDatasetComponentTest.java
src/test/java/org/generationcp/ibpworkbench/study/TableViewerComponentTest.java
src/test/java/org/generationcp/ibpworkbench/study/TableViewerDatasetTableTest.java

Unit test modified: 
ExportListAsDialogTest.testExportListAsXLS
ExportListAsDialogTest.testExportListAsCSV
ExportListAsDialogTest.testExportListForGenotypingOrderAction
OpenSelectDatasetForExportActionTest.testPopulateProjectNameAndFilePaths
RepresentationDatasetComponentTest.testExportToExcelAction
ResultsComponentTest.testExportButtonClickAction
RunMultiSiteActionTest.testButtonClickServerAppIsTrue
RunSingleSiteActionTest.testButtonClick
TableViewerComponentTest.testExportToExcelActionStudyNameIsNotNull
IBP-2634-FixFailingUnitTests

IBP-2634-FixFailingUnitTests

---

src/main/jhipster/src/main/webapp/app/navbar/navbar.component.ts

IBP-4449 make account resource return user detail dto instead user dto

---

src/main/jhipster/src/main/webapp/app/label-printing/label-printing.route.ts

IBP-4205 Adding missing permissions 

---

src/main/jhipster/src/main/webapp/app/entities/germplasm/attribute/germplasm-attribute-modal.component.html

IBP-4578  Disable dropdown variable in edits Passports or Attributes in Germplasm Details

---

src/main/java/org/generationcp/ibpworkbench/germplasm/GermplasmPedigreeTreeComponent.java
src/main/java/org/generationcp/ibpworkbench/germplasm/pedigree/CreatePedigreeGraph.java
src/test/java/org/generationcp/ibpworkbench/germplasm/pedigree/CreatePedigreeGraphTest.java

Set Arrow's color, if derivative/unknown male parent 
Unit test for create pedigree graph

IBP-4395-NodeForUnknownMaleKnownFemale

---

src/main/jhipster/src/main/webapp/app/germplasm-details/basic-details/basic-details-pane.component.html
src/main/jhipster/src/main/webapp/app/germplasm-details/basic-details/basic-details-pane.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-details/lists/lists-pane.component.html
src/main/jhipster/src/main/webapp/app/germplasm-details/lists/lists-pane.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-details/observations/observations-pane.component.html
src/main/jhipster/src/main/webapp/app/germplasm-details/observations/observations-pane.component.ts
src/main/jhipster/src/main/webapp/app/shared/germplasm/model/germplasm.model.ts
src/main/jhipster/src/main/webapp/app/shared/germplasm/service/germplasm-details.url.service.ts

Also IBP-4527 disable study links in germplasm origin when study is from another program

IBP-4582 inter module links with menu highlighting

---

src/main/java/org/generationcp/ibpworkbench/germplasm/GermplasmPedigreeTreeComponent.java
src/test/java/org/generationcp/ibpworkbench/germplasm/GermplasmPedigreeTreeComponentTest.java

If gid is zero (unknown) check if have nodes, if true do not add unknown but add children. Else add unknown.
Added junit test for unknown male derivative (unknown with children)
Added junit test unknown male and female parent 
Unit test using derivative with unknown male, generative with unknown male, generative with multiple male parents

IBP-4395-GermplsmTreeUnknownParent

---

src/main/java/org/generationcp/breeding/manager/listmanager/listcomponent/ListViewActionMenu.java
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-manager.route.ts
src/test/java/org/generationcp/breeding/manager/listmanager/listcomponent/ListViewActionMenuTest.java

IBP-4572 verify correct imlementation of crop management permission

---

src/main/jhipster/package.json
src/main/jhipster/src/main/webapp/app/shared/germplasm/service/germplasm-details.url.service.ts
src/main/jhipster/src/main/webapp/app/shared/pedigree-graph/pedigree-graph.component.css
src/main/jhipster/src/main/webapp/app/shared/pedigree-graph/pedigree-graph.component.html
src/main/jhipster/src/main/webapp/app/shared/pedigree-graph/pedigree-graph.component.ts
src/main/jhipster/yarn.lock

IBP-4676 Open Germplasm Details Page On Graph Node Click

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/import/germplasm-import-matches.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/selector/germplasm-selector.component.html

- group id in germplasm search
- group id in germplasm selector
- gid and name in germplasm import matches

IBP-4714: Migrate some missing germplasm-details links

---

src/main/web/src/js/login.js

Add new oidc parameters to login/authorize page
Relates to https://github.com/PhenoApps/Field-Book/pull/208

IBP-4622: Basic KSU Field-book OpenId Connect setup

---

src/main/resources/workbench.properties

Moved prop to BMSConfig, removed unused property

---

pom.xml
src/main/resources/ibpworkbench-servlet.xml

IBP-4674 Force JavaEmailSender to use TLS 1.2

---

src/main/web/src/apps/ontology/app-components/add-variable-view/addVariableView.html
src/main/web/src/apps/ontology/app-components/add-variable-view/addVariableView.js
src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.html
src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.js
src/main/web/src/resources/locale-en.json

IBP-4744 enforce variable name and alias uniqueness within a crop

---

src/main/resources/applicationContext.xml

Please, review
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/545
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1089
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1016

IBP-4607 Get all name types and Create a new one.

---

src/main/java/org/generationcp/ibpworkbench/ui/project/create/ProjectBasicDetailsComponent.java
src/main/jhipster/src/main/webapp/app/navbar/navbar.component.ts

Merge "Add Program" fixes to main hotfix branch IBP-4816

IBP-4800 hotfix add program

---

src/main/java/org/generationcp/ibpworkbench/service/ProgramService.java
src/main/resources/applicationContext.xml

Impementing services to add and remove users from a program

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-search.component.ts
src/main/jhipster/src/main/webapp/i18n/en/germplasm-manager.json

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/90
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/560

IBP-4836 actions failed when filter applied in table returns no results

---

src/main/java/org/generationcp/ibpworkbench/controller/JHipsterController.java
src/main/java/org/generationcp/ibpworkbench/controller/UserProgramController.java
src/main/jhipster/src/main/webapp/app/app.constants.ts
src/main/jhipster/src/main/webapp/app/entities/sample/sample-manager.component.ts
src/main/jhipster/src/main/webapp/app/navbar/navbar.component.ts
src/main/jhipster/src/main/webapp/app/shared/auth/account.service.ts
src/main/jhipster/src/main/webapp/app/shared/service/program-usage.service.ts
src/main/jhipster/src/main/webapp/index.html

IBP-4829 several permission issues when a program is set in context

---

src/main/jhipster/src/main/webapp/app/shared/key-sequence-register/service/key-sequence-register.service.ts

IBP-4630 Added programUUID paramter to endpoint

---

src/main/jhipster/src/main/webapp/app/entities/user-profile/user-profile-update-dialog.component.html
src/main/web/src/appsNg2/admin/app/shared/validators/email-validator.component.ts
src/main/web/src/appsNg2/admin/app/users/user-card.component.html

Please revew.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1112
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/570

IBP-4908 cannot use email grather than 40 characters

---

src/main/jhipster/src/main/webapp/app/file-manager/file-manager.component.html
src/main/jhipster/src/main/webapp/app/file-manager/file-manager.component.ts
src/main/jhipster/src/main/webapp/app/shared/ontology/model/variable-filter-request.ts
src/main/jhipster/src/main/webapp/app/shared/variable-select/variable-select.component.ts

Frontend:
- Add datasetId param to file manager and pass it to variable-select
- make variable select use /variables/filter, filter by dataset and
variableTypeId, remove  client-side variable-type filtering

IBP-4917: Associate files only to dataset variables

---

src/main/jhipster/src/main/webapp/content/release-notes/19.0.html

IBP-4954 Update v19 release notes.

---

src/main/jhipster/src/main/webapp/app/metadata-manager/name-type/name-type.component.html
src/main/jhipster/src/main/webapp/app/metadata-manager/name-type/name-type.component.ts
src/main/jhipster/src/main/webapp/app/shared/column-filter/column-filter.component.css
src/main/jhipster/src/main/webapp/app/shared/column-filter/inline/column-filter-inline.component.html
src/main/jhipster/src/main/webapp/app/shared/column-filter/inline/column-filter-inline.component.ts
src/main/jhipster/src/main/webapp/app/shared/name-type/service/name-type.service.ts

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1126
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/577

IBP-4918 implement name types filter

---

src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

Map gid to germplasmUUID before filtering by germplasm. This is a rather simple fix, for other more complex options see IBP-4981

IBP-4981 IBP-4984: Fix germplasmDbId (germplasmUUID) filter in graphical queries

---

src/main/jhipster/src/main/webapp/content/release-notes/19.0.html

Fixing Product board URL

---

src/main/java/org/generationcp/ibpworkbench/ui/project/create/ProjectBasicDetailsComponent.java
src/test/java/org/generationcp/ibpworkbench/ui/project/create/ProjectBasicDetailsComponentTest.java

- instead of a disabled dropdown, crop fields is changed to a static text field in Manage Program Settings screen on update mode.
- skip validation of Crop Type on update

IBP-4830: change crop to static text when updating program

---

src/main/java/org/generationcp/ibpworkbench/service/ProgramService.java
src/test/java/org/generationcp/ibpworkbench/service/ProgramServiceTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1147
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/600

IBP-5046 implement POST and DELETE program favorites Api

---

src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

- columns with character data (non-numeric data) should still be displayed

IBP-5024: fix display of character data in BrAPI Graphical Filtering

---

src/main/jhipster/src/main/webapp/app/navbar/navbar.component.ts

Display BMS version in sidebar same as in login page

---

src/main/web/package.json
src/main/web/yarn.lock

IBP-5224 Fix Blank Map In Georeference 

---

src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.html
src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.js
src/main/web/src/resources/locale-en.json

Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/624
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1175

IBP-4793 can not edit or delete system variables

---

src/main/web/src/apps/ontology/shared-services/variables.js

- remove passing of undefined authToken to prevent nullpointerrexception

IBP-5268: Ontology caching issue fix

---

src/main/jhipster/src/main/webapp/app/germplasm-list/germplasm-list-search.component.html
src/main/jhipster/src/main/webapp/i18n/en/germplasm-list.json

Reverts IntegratedBreedingPlatform/Workbench#611

Revert "IBP-5282: show 'Invalid' instead of 'null' when the date is invalid"

---

src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/germplasm-list/germplasm-list-add.component.html
src/main/jhipster/src/main/webapp/app/shared/column-filter/column-filter.component.html

(merge after https://github.com/IntegratedBreedingPlatform/Workbench/pull/619)

IBP-5262: add data-test attribute needed for edit list metadata cypress test

---

src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.css
src/main/jhipster/src/main/webapp/app/label-printing/label-printing.component.html

IBP-5346 add scroll table in export data label

---

src/main/jhipster/src/main/webapp/app/shared/tree/germplasm/germplasm-tree.service.ts
src/main/jhipster/src/main/webapp/app/shared/tree/tree-node.model.ts
src/main/jhipster/src/main/webapp/app/shared/tree/tree-table.component.html
src/main/jhipster/src/main/webapp/app/shared/tree/tree.component.ts

- add locked indicator in tree node
- update models to retrieve locked indicator

IBP-5364: add locked indicator in browse for list

---

src/main/jhipster/src/main/webapp/app/shared/tree/germplasm/germplasm-tree.service.ts
src/main/jhipster/src/main/webapp/app/shared/tree/tree-node.model.ts
src/main/jhipster/src/main/webapp/app/shared/tree/tree-table.component.html
src/main/jhipster/src/main/webapp/app/shared/tree/tree.component.ts

pre-requisite: data retrieval handled in https://github.com/IntegratedBreedingPlatform/Workbench/pull/641 - should be merged before this

IBP-5355: prevent moving locked list to a different folder

---

src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import-review.component.html
src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import-review.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/import/germplasm-import-review.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/import/germplasm-import-review.component.ts
src/main/jhipster/src/main/webapp/app/shared/util/file-utils.ts
src/main/jhipster/src/main/webapp/i18n/en/germplasm-list.json
src/main/jhipster/src/main/webapp/i18n/en/germplasm-manager.json

IBP-5368 export view table in excel

---

src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.html
src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.ts

Plese, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/653
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1209

IBP-5357 Lock/Unlock and delete permissions in Germplasm Lists.

---

src/main/jhipster/src/main/webapp/app/entities/sample/tree-table/sample-tree.service.ts
src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.ts
src/main/jhipster/src/main/webapp/app/shared/tree/germplasm/germplasm-tree.service.ts
src/main/jhipster/src/main/webapp/app/shared/tree/tree.component.ts

Fixes issue when moving to and from crop list

IBP-5412: Don't send programUUID in move to folders (TODO IBP-5413)

---

src/main/jhipster/src/main/webapp/app/shared/tree/tree.component.ts
src/main/jhipster/src/main/webapp/i18n/en/tree-table.json

(merge https://github.com/IntegratedBreedingPlatform/Workbench/pull/645 fiirst)

IBP-5372: fix selecting multiple lists

---

src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import.component.ts
src/main/jhipster/src/main/webapp/i18n/en/germplasm-list.json

IBP-5409 Enforce ENTRY_NO column and values are present in import lists file

---

src/main/jhipster/src/main/webapp/app/program-settings-manager/tabs/basic-details/basic-details-pane.component.html

Fix minor.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1230
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/668

IBP-4838 manage program settings beta

---

src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import-multi-matches.component.html
src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import-multi-matches.component.ts
src/main/jhipster/src/main/webapp/i18n/en/germplasm-list.json

IBP-5420 Implement logic to use the same match for all occurrences.

---

src/main/jhipster/src/main/webapp/app/shared/column-filter/column-filter.component.ts

IBP-5452: Fix error encountered on removing attribute and name type f

---

src/main/jhipster/src/main/webapp/app/crop-settings-manager/locations/location-edit-dialog.component.ts
src/main/jhipster/src/main/webapp/app/crop-settings-manager/locations/locations-pane.component.html
src/main/jhipster/src/main/webapp/app/crop-settings-manager/locations/locations-pane.component.ts
src/main/jhipster/src/main/webapp/app/entities/location/location.component.ts
src/main/jhipster/src/main/webapp/app/program-settings-manager/tabs/locations/locations-pane.component.ts
src/main/jhipster/src/main/webapp/app/shared/location/service/location.service.ts

Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/684

IBP-5540 restrictions on location management

---

src/main/jhipster/src/main/webapp/app/germplasm-list/import/germplasm-list-import-review.component.ts

Ensure unique germplasm are displayed in the name matches

---

src/main/jhipster/src/main/webapp/app/germplasm-list/list-columns.component.html
src/main/jhipster/src/main/webapp/app/germplasm-list/list-columns.component.ts
src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.ts

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/691
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1258

IBP-5590-Limit-add-column-in-germplasm-list

---

src/main/jhipster/src/main/webapp/app/shared/germplasm-list/service/germplasm-list.service.ts
src/main/jhipster/src/main/webapp/app/shared/germplasm/service/germplasm.service.ts
src/main/jhipster/src/main/webapp/app/shared/inventory/service/lot.service.ts

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/702
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1081
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/102

IBP-4985_remove_single_entity_response

---

src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

- affected by change in IBP-4985

IBP-5760 -  adjust search ID retrieval to match new response format 

---

src/main/java/org/generationcp/breeding/manager/application/BreedingManagerWindowGenerator.java
src/main/java/org/generationcp/browser/study/listeners/ViewStudyDetailsButtonClickListener.java
src/main/java/org/generationcp/ibpworkbench/actions/OpenSelectDatasetForExportAction.java
src/main/java/org/generationcp/ibpworkbench/actions/RunMultiSiteAction.java
src/main/java/org/generationcp/ibpworkbench/germplasm/GermplasmListComponent.java
src/main/resources/applicationContext.xml
src/test/java/org/generationcp/browser/study/listeners/ViewStudyDetailsButtonClickListenerTest.java
src/test/java/org/generationcp/ibpworkbench/actions/OpenSelectDatasetForExportActionTest.java
src/test/java/org/generationcp/ibpworkbench/actions/RunMultiSiteActionTest.java

IBP-5736-create-tool-service

---

src/main/java/org/generationcp/ibpworkbench/study/RepresentationDatasetComponent.java
src/main/java/org/generationcp/ibpworkbench/study/TableViewerDatasetTable.java
src/main/java/org/generationcp/ibpworkbench/study/containers/RepresentationDataSetQuery.java
src/main/jhipster/src/main/webapp/app/shared/shared.module.ts

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1102
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/727
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1306

IBP-5774-Add_female_and_male_parents_columns_in_Germplasm_and_checks_tab

---

src/main/jhipster/src/main/webapp/app/program-settings-manager/tabs/basic-details/basic-details-pane.component.html
src/main/jhipster/src/main/webapp/app/shared/locations-select/locations-select.component.ts

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1113

IBP-5825-location_selector_component_issues

---

src/main/web/src/apps/ontology/app-components/method-details-view/methodDetails.html
src/main/web/src/apps/ontology/app-components/method-details-view/methodDetails.js
src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.html
src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.js
src/main/web/src/resources/locale-en.json

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1328
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/743

IBP-5835-ontology_method_for_sta_brapp

---

src/main/jhipster/src/main/webapp/app/germplasm-list/list.component.ts
src/main/jhipster/tsconfig-aot.json
src/main/jhipster/tsconfig.json

Map can be iterated in insertion order, useful for selected items in tables, where we've been using Object until now.
**Regression testing** is needed.

IBP-5826: frontend: target ES6 for compilation, to be able to use Map and sort COP

---

src/main/jhipster/src/main/webapp/app/entities/breeding-method/breeding-method.component.ts
src/main/jhipster/src/main/webapp/app/entities/breeding-method/breeding-method.route.ts
src/main/jhipster/src/main/webapp/app/shared/breeding-method/service/breeding-method.service.ts

IBP-5872: add breeding method modal on click of field in germplasm and checks

---

src/main/java/org/generationcp/ibpworkbench/ui/breedingview/multisiteanalysis/MultiSiteAnalysisSelectPanel.java
src/main/java/org/generationcp/ibpworkbench/ui/breedingview/singlesiteanalysis/SingleSiteAnalysisGenotypesComponent.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/363

IBP-5951-SSA_missing_ENTRY_NO_from_specify_Genotypes_dropdown

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/selector/germplasm-selector.component.html

IBP-5936: fix immediate source name display in germplasm selector modal

---

src/main/web/src/appsNg2/admin/app/users/users-datagrid.component.ts

IBP-5978-RestrictNumberOfActiveUsers

---

src/main/java/org/generationcp/ibpworkbench/controller/AuthenticationController.java
src/main/resources/workbench.properties
src/main/web/src/js/login.js
src/main/web/src/pages/login.html
src/main/web/src/sass/login.scss

- error on expired licenses, warning on expiring in 30 days
- add property to enable/disable the validation

IBP-5977: implement design license validation on login

---

src/main/web/package.json

https://github.com/IntegratedBreedingPlatform/brapi-sync/pull/16

IBP-5777 IBP-5942 IBP-5981 Pedigree sync fixes

---

src/main/java/org/generationcp/ibpworkbench/controller/AuthenticationController.java
src/main/java/org/generationcp/ibpworkbench/service/WorkbenchUserService.java
src/main/resources/workbench.properties
src/main/web/src/js/login.js
src/main/web/src/pages/login.html
src/main/web/yarn.lock
src/main/webapp/WEB-INF/i18n/Messages.properties
src/test/java/org/generationcp/ibpworkbench/controller/AuthenticationControllerTest.java
src/test/java/org/generationcp/ibpworkbench/service/WorkbenchUserServiceTest.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSConfig/pull/124

IBP-3009_remove_code_used_for_desktop

---

src/main/java/org/generationcp/ibpworkbench/service/WorkbenchUserService.java

IBP-6074-Delete-addUser

---

src/main/web/src/pages/BrAPI-Graphical-Queries/index.html
src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/373

IBP-6129 Update user manual links for v23.

---

src/main/web/src/pages/BrAPI-Graphical-Queries/main.js

…ies dropdown within graphical queries

IBP-6131-remove-org-ibp-api-rest-study-study-resource-get-studies-and-instead-use-org-ibp-api-rest-study-study-resource-search-studies

---

src/main/jhipster/src/main/webapp/app/site-admin/model/permission.model.ts
src/main/jhipster/src/main/webapp/app/site-admin/site-admin.module.ts
src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/role-edit-dialog.component.css
src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/role-edit-dialog.component.html
src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/role-edit-dialog.component.ts

IBP-5925_permission_tree_UX_improvements

---

src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/role-edit-dialog.component.ts

IBP-6284 SITE admin Permission Tree

---

src/main/jhipster/src/main/webapp/app/study-manager/advance/advance-samples.component.html
src/main/jhipster/src/main/webapp/app/study-manager/advance/advance-study.component.html

IBP-6247-TickFaveBreedingMethodsCheckbox

---

src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.html
src/main/web/src/apps/ontology/shared-components/select/select.html
src/main/web/src/apps/ontology/shared-components/select/select.js

…show the correct element for PSM value
IBP-6172

IBP-6172-PSMFieldsIssue

---

src/main/jhipster/src/main/webapp/app/shared/pedigree-graph/pedigree-graph.component.ts

IBP-6338-HighlightSelectedGermplasmAfterGraphReload

---

src/main/java/org/generationcp/ibpworkbench/actions/breedingview/singlesiteanalysis/RunSingleSiteAction.java
src/main/java/org/generationcp/ibpworkbench/ui/breedingview/singlesiteanalysis/SingleSiteAnalysisStudyDetailsComponent.java

IBP-6346 replace use StringUtils from mysql library

---

src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/roles-pane.component.html
src/main/jhipster/src/main/webapp/app/site-admin/tabs/roles/roles-pane.component.ts
src/main/jhipster/src/main/webapp/app/site-admin/tabs/users/users-pane.component.html
src/main/jhipster/src/main/webapp/app/site-admin/tabs/users/users-pane.component.ts
src/main/jhipster/src/main/webapp/app/site-admin/tabs/users/users-role-dialog.component.ts

IBP-6344 site admin assign role to user sort names in alphabetic order asc

---

src/main/web/src/apps/ontology/app-components/variable-details-view/variableDetails.html
src/main/web/src/resources/locale-en.json

IBP-5758-IncludeLotsCountInVariableMetadata

---

src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/details/inventory-details.module.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/details/inventory-details.route.ts
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/details/transaction-details-modal.component.html
src/main/jhipster/src/main/webapp/app/germplasm-manager/inventory/details/transaction-details-modal.component.ts

- add link for stock id to show lot transactions
- remove unnecessary transaction types

IBP-4511: improvements for studies inventory tab

---

src/main/web/src/js/reset-password.js

- allow submitting weak passwords but display warning message

IBP-6401: remove front end password strength validation

---

src/main/jhipster/src/main/webapp/content/release-notes/25.0.html

IBP-6423-AddV25ReleaseNotes
